#!/bin/bash

# Exit immediately if any command fails
set -e

# Define the line to add in the pg_hba.conf file
pg_line="host    $MAAS_DBNAME    $MAAS_DBUSER    0/0     md5"

# Path to the pg_hba.conf file
pg_hba_conf="/etc/postgresql/16/main/pg_hba.conf"

sudo snap install maas

sudo apt install -y postgresql

# Create a suitable PostgreSQL user
sudo -i -u postgres psql -c "CREATE USER \"$MAAS_DBUSER\" WITH ENCRYPTED PASSWORD '$MAAS_DBPASS'"

# Create the MAAS database
sudo -i -u postgres createdb -O "$MAAS_DBUSER" "$MAAS_DBNAME"

# Check if the line already exists in the file
if sudo grep -Fxq "$pg_line" "$pg_hba_conf"
then
    echo "The line already exists in $pg_hba_conf"
else
    # Add the line to the pg_hba.conf file
    echo "$pg_line" | sudo tee -a "$pg_hba_conf" > /dev/null
fi

sudo maas init region+rack --database-uri "postgres://$MAAS_DBUSER:$MAAS_DBPASS@$HOSTNAME/$MAAS_DBNAME" --maas-url http://192.168.44.5:5240/MAAS

sudo maas createadmin --username=$MAAS_USERNAME --password=$MAAS_PASSWORD --email=$MAAS_EMAIL

